# Generated by Django 5.2.1 on 2025-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('read', models.BooleanField(default=False)),
                ('year_read', models.IntegerField()),
            ],
        ),
    ]
