# Generated by Django 5.2.1 on 2025-06-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookshelf',
            new_name='Books',
        ),
    ]
