# Generated by Django 5.2.1 on 2025-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_book_genre_alter_book_year_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_read',
            field=models.IntegerField(),
        ),
    ]
