# Generated by Django 5.2.1 on 2025-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_alter_book_year_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_read',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
